name: Supabase Keep-Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Alive
        run: |
          curl -X POST "https://${{ secrets.SUPABASE_PROJECT }}.supabase.co/rest/v1/rpc/keep_alive" \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Prefer: params=single-object"
